use crate::utils::github_client::GithubClient;
use async_trait::async_trait;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::error::AppError;

use super::{Fetcher, SourceType, UpdateEventType};
/// Repository represents a GitHub repository
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Repository {
    /// Unique identifier for the repository in our system
    pub id: i32,

    /// Repository owner (username or organization)
    pub owner: String,

    /// Repository name
    pub name: String,

    /// GitHub token
    pub token: Option<String>,
}

impl Repository {
    /// Create a new repository with minimal information
    pub fn new(id: i32, owner: String, name: String) -> Self {
        Self {
            id,
            owner,
            name,
            token: None,
        }
    }

    /// Get the full repository name in the format "owner/name"
    pub fn full_name(&self) -> String {
        format!("{}/{}", self.owner, self.name)
    }

    pub fn with_token(mut self, token: String) -> Self {
        self.token = Some(token);
        self
    }
}

#[async_trait]
impl Fetcher for Repository {
    async fn fetch_updates(&self, since: DateTime<Utc>) -> Result<String, AppError> {
        let client = if let Some(token) = &self.token {
            GithubClient::with_token(token.clone()).unwrap()
        } else {
            GithubClient::anonymous().unwrap()
        };
        let updates = client
            .fetch_updates(
                &self.owner,
                &self.name,
                None,
                since,
                vec![UpdateEventType::Issue, UpdateEventType::PullRequest],
            )
            .await?;

        // title
        let mut report = String::new();
        report.push_str(&format!("# Update Report: {}\n\n", self.full_name()));
        report.push_str(&format!(
            "## Period: {} to {}\n\n",
            since.format("%Y-%m-%d"),
            Utc::now().format("%Y-%m-%d")
        ));

        // source information
        report.push_str("## Source Information\n\n");
        report.push_str(&format!("- **Type**: {}\n", SourceType::GitHub));
        report.push_str(&format!("- **Name**: {}\n", self.full_name()));
        report.push('\n');

        // summary
        report.push_str("## Summary\n\n");
        let mut prs = Vec::new();
        let mut issues = Vec::new();

        report.push_str(&format!("- **Total Updates**: {}\n", updates.len()));
        for update in updates {
            match update.event_type {
                UpdateEventType::PullRequest => prs.push(update),
                UpdateEventType::Issue => issues.push(update),
                _ => continue,
            }
        }

        report.push_str(&format!("- **Pull Requests**: {}\n", prs.len()));
        report.push_str(&format!("- **Issues**: {}\n", issues.len()));
        report.push('\n');

        // pull requests details
        if !prs.is_empty() {
            report.push_str("## Pull Requests\n\n");
            for pr in prs {
                report.push_str(&format!("### {}\n\n", pr.title));
                report.push_str(&format!(
                    "- **Date**: {}\n",
                    pr.event_date.format("%Y-%m-%d %H:%M:%S")
                ));
                report.push_str(&format!("- **Author**: {}\n", pr.author));
                report.push_str(&format!("- **URL**: {}\n", pr.url));
                report.push_str(&format!("- **Description**:\n\n{}\n", pr.description));
                report.push('\n');
            }
        }

        // issues details
        if !issues.is_empty() {
            report.push_str("## Issues\n\n");
            for issue in issues {
                report.push_str(&format!("### {}\n\n", issue.title));
                report.push_str(&format!(
                    "- **Date**: {}\n",
                    issue.event_date.format("%Y-%m-%d %H:%M:%S")
                ));
                report.push_str(&format!("- **Author**: {}\n", issue.author));
                report.push_str(&format!("- **URL**: {}\n", issue.url));
                report.push_str(&format!("- **Description**:\n\n{}\n", issue.description));
                report.push('\n');
            }
        }

        // footer
        report.push_str(&format!(
            "---\nGenerated by XiaoTian at {}\n",
            Utc::now().format("%Y-%m-%d %H:%M:%S")
        ));

        Ok(report)
    }
}
